// Code generated by cmd/sync-oss. DO NOT EDIT.
// Source: products.RegisteredProductNames() filtered by synclist.json

package helpers

import (
	"github.com/DingTalk-Real-AI/dingtalk-workspace-cli/internal/executor"
	"github.com/spf13/cobra"
)

type wukongHandler struct {
	name    string
	buildFn func() *cobra.Command
}

func (h wukongHandler) Name() string { return h.name }
func (h wukongHandler) Command(_ executor.Runner) *cobra.Command {
	return h.buildFn()
}

func init() {
	products := []struct {
		name string
		fn   func() *cobra.Command
	}{
		{"agoal", newAgoalCommand},
		{"aisearch", newAisearchCommand},
		{"aitable", newAitableCommand},
		{"attendance", newAttendanceCommand},
		{"calendar", newCalendarCommand},
		{"chat", newChatCommand},
		{"contact", newContactCommand},
		{"devdoc", newDevdocCommand},
		{"ding", newDingCommand},
		{"doc", newDocCommand},
		{"drive", newDriveCommand},
		{"hrbrain", newHrbrainCommand},
		{"html", newHTMLCommand},
		{"live", newLiveCommand},
		{"mail", newMailCommand},
		{"markdown", newMarkdownCommand},
		{"minutes", newMinutesCommand},
		{"oa", newOaCommand},
		{"report", newReportCommand},
		{"sheet", newSheetCommand},
		{"todo", newTodoCommand},
		{"wiki", newWikiCommand},
	}
	for _, p := range products {
		p := p
		RegisterPublic(func() Handler {
			return wukongHandler{name: p.name, buildFn: p.fn}
		})
	}
}
